name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.2', '7.3', '7.4']
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: |
        curl -sS https://getcomposer.org/installer | php -- --filename=composer
        composer install --no-interaction --prefer-source
        vendor/bin/test
